returning cleanup, added clearer errors in deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -89,15 +89,30 @@ jobs:
       
       - name: Unzip website on the server to root folder
         run: |
-          curl -X GET "https://${{ secrets.siteDomain }}/handlezipfiles.php?unzip=website.zip&target=current"
+          response=$(curl -X GET "https://${{ secrets.siteDomain }}/handlezipfiles.php?unzip=website.zip&target=current")
+          echo "$response"
+          if echo "$response" | grep -Eqi "error|failed"; then
+            echo "Error detected."
+          exit 1
+          fi
 
       - name: Unzip stylesheets on the server to stylesheets folder
         run: |
-          curl -X GET "https://${{ secrets.siteDomain }}/handlezipfiles.php?unzip=stylesheets.zip&target="
+          response=$(curl -X GET "https://${{ secrets.siteDomain }}/handlezipfiles.php?unzip=stylesheets.zip&target=")
+          echo "$response"
+          if echo "$response" | grep -Eqi "error|failed"; then
+            echo "Error detected."
+          exit 1
+          fi
 
       - name: Unzip templates on the server to templates folder
         run: |
-          curl -X GET "https://${{ secrets.siteDomain }}/handlezipfiles.php?unzip=templates.zip&target="
+          response=$(curl -X GET "https://${{ secrets.siteDomain }}/handlezipfiles.php?unzip=templates.zip&target=")
+          echo "$response"
+          if echo "$response" | grep -Eqi "error|failed"; then
+            echo "Error detected."
+          exit 1
+          fi
 
   update-stylesheets:
     needs: [update-database, update-files]
@@ -134,7 +149,12 @@ jobs:
 
       - name: Rebuild stylesheets
         run: |
-          curl -X GET "https://${{ secrets.siteDomain }}/handlestylesheetsandtemplates.php?rebuild=stylesheets&fromconsole=true"
+          response=$(curl -X GET "https://${{ secrets.siteDomain }}/handlestylesheetsandtemplates.php?rebuild=stylesheets&fromconsole=true")
+          echo "$response"
+          if echo "$response" | grep -Eqi "error|failed"; then
+            echo "Error detected."
+          exit 1
+          fi
        
   update-templates:
     needs: [update-database, update-files]
@@ -145,32 +165,43 @@ jobs:
 
       - name: Rebuild templates
         run: |
-          curl -X GET "https://${{ secrets.siteDomain }}/handlestylesheetsandtemplates.php?rebuild=templates&force=true&fromconsole=true"
+          response=$(curl -X GET "https://${{ secrets.siteDomain }}/handlestylesheetsandtemplates.php?rebuild=templates&force=true&fromconsole=true")
+          echo "$response"
+          if echo "$response" | grep -Eqi "error|failed"; then
+            echo "Error detected."
+          exit 1
+          fi
 
 
-  # cleanup:
-  #   needs: [update-stylesheets, update-templates]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Install lftp
-  #       run: sudo apt-get install -y lftp
+  cleanup:
+    needs: [update-stylesheets, update-templates]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install lftp
+        run: sudo apt-get install -y lftp
 
-  #     - name: Remove templates and stylesheets folders
-  #       run: |
-  #         curl -X GET "https://${{ secrets.siteDomain }}/handlestylesheetsandtemplates.php?cleanup=true&fromconsole=true"
+      - name: Remove templates and stylesheets folders
+        run: |
+            response=$(curl -X GET "https://${{ secrets.siteDomain }}/handlestylesheetsandtemplates.php?cleanup=true&fromconsole=true")
+            echo "$response"
+            if echo "$response" | grep -Eqi "error|failed"; then
+              echo "Error detected."
+            exit 1
+            fi
 
-  #     - name: Remove zip files and PHP cleanup scripts from server
-  #       env:
-  #         FTP_HOST: ${{ secrets.FTP_HOST }}
-  #         FTP_USER: ${{ secrets.FTP_USERNAME }}
-  #         FTP_PASS: ${{ secrets.FTP_PASSWORD }}
-  #       run: |
-  #         lftp -u $FTP_USER,$FTP_PASS $FTP_HOST <<EOF
-  #         set ssl:verify-certificate no
-  #         rm -f ./website.zip
-  #         rm -f ./stylesheets.zip
-  #         rm -f ./templates.zip
-  #         rm -f ./handlestylesheetsandtemplates.php
-  #         rm -f ./handlezipfiles.php
-  #         bye
-  #         EOF
+
+      - name: Remove zip files and PHP cleanup scripts from server
+        env:
+          FTP_HOST: ${{ secrets.FTP_HOST }}
+          FTP_USER: ${{ secrets.FTP_USERNAME }}
+          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
+        run: |
+          lftp -u $FTP_USER,$FTP_PASS $FTP_HOST <<EOF
+          set ssl:verify-certificate no
+          rm -f ./website.zip
+          rm -f ./stylesheets.zip
+          rm -f ./templates.zip
+          rm -f ./handlestylesheetsandtemplates.php
+          rm -f ./handlezipfiles.php
+          bye
+          EOF
